config/routes.rb
Rails.application.routes.draw do

  resources :recipes, :categories
    root to: 'home#index'
    get '/about', to: 'home#about', as: 'about'
    get '/contact', to: 'home#contact', as: 'contact'
    get '/admin', to: 'admin#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    belongs_to :category
    validates_presence_of :title, :ingredients, :instructions
    validates :title, uniqueness: true

    def self.find_all_by_query(query)
        query = query.downcase
        query = "%#{query}%"
        
        Recipe.where(['lower(title) like ?', query])
    end    

    def self.find_all_by_query(query)
        query = query.downcase
        query = "%#{query}%"
        Recipe.where(['lower(title) like ?
        OR lower(ingredients) like ?
        OR lower(instructions) like ?',
        query, query, query])
    end

end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    def self.authenticate(username, password) 
        user = User.where(username: username).first 
        user && user.authenticate(password)
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController  
before_action :authenticate

  def index
    @title = 'index'
  end

private
  def authenticate
    if user = authenticate_with_http_basic {|user, password| User.authenticate(user, password)}
    session[:user_id] = user.id
    session[:logged_in] = true else
    request_http_basic_authentication
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception

  before_action :set_title, only: [:show, :edit, :update, :destroy]
  
  helper_method :current_user
  
  def set_title
    @title = 'Cookbook'
  end
  
    private
        def authenticate
            if user = authenticate_with_http_basic {|user, password| User.authenticate(user, password)}
                session[:user_id] = user.id
                session[:logged_in] = true 
            else
                request_http_basic_authentication
            end
        end
    
    helper_method :logged_in?
    def logged_in? 
        session[:logged_in]

    end

  private
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
    @title = 'index'
  end

  def show
    @title = 'Show Category'
    @recipes = @category.recipes
  end
  
  def new
    @category = Category.new
    @title = 'New Category'
  end

  def edit
  @title = 'Edit Category'

  end

  def create
    @category = Category.new(category_params)
    @title = 'Create Category'

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
  @title = 'Update Category'
  
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    @title = 'Delete Category'
    
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_category
      @category = Category.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index  
    @number_of_recipes = Recipe.count
    @latest_recipe = Recipe.last
  end 

  def about
  end
  
  def contact
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :get_categories, :only =>[:new, :edit, :create, :update]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, :except => [:index, :show]

  def index

    if params[:q]
       @recipes = Recipe.find_all_by_query(params[:q])
    else
        @recipes = Recipe.all
    end
    @title = 'index'
  end

  def show
  @title = 'Show Recipe'
  end

  def new
    @recipe = Recipe.new
    #@categories = Category.all.collect{|c| [c.name, c.id]}
    @title = 'New Recipe'
  end

  def edit
  @title = 'Edit Recipe'
  #@categories = Category.all.collect{|c| [c.name, c.id]}
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @title = 'Create Recipe'

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

  @title = 'Update Recipe'
  
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy
    @title = 'Delete Recipe'
    
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_recipe
      @recipe = Recipe.includes(:category).find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:title, :ingredients, :instructions, :category_id)
    end
    
    def get_categories
      @categories = Category.all.collect{|c| [c.name, c.id] }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/admin/index.html.erb
<h1>Admin Page</h1>

<% if logged_in? %>
    You are logged in as <%= current_user.username %>
<% end %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>*<br>
    <%= f.text_field :name %>
  </div>
  <div><small>* - denotes required field.</small></div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>

  <tr> 
    <th>Name</th>
    <th>Last Updated</th>
    <th colspan="2">&nbsp;</th>
  </tr>

  <% @categories.each do |category| %>
    <tr>
      <td><%= link_to category.name, category %></td>
      <td><%= time_ago_in_words(category.updated_at) %> ago</td>
      <td><%= link_to 'Edit', edit_category_path(category) %></td>
      <td><%= button_to 'Destroy', category, confirm: 'Are you sure?', method: :delete %></td>     
    </tr>
  <% end %>
</table>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<article>
  <header>
    <h2>
      <%= @category.name %>
      [ <%= link_to 'Edit', edit_category_path(@category) %> ]
    </h2>
  </header>
    <p>Recipes:</p>
  
       <% @recipes.each do |recipe| %>         
           <div>
                <%= link_to recipe.title,recipe,class:"btn btn-primary btn-block" %>
           </div>
       <%end%>
  
</article>

<p><%= link_to 'Back', categories_path %></p>

app/views/home/about.html.erb
<h2>About</h2>
<p>This is a simple cookbook application I wrote. I hope you like it.</p>

app/views/home/contact.html.erb
<h2>Contact Us!</h2>
<p>There are <%= @number_of_recipes %> recipes total, but with your help we can have more!</p>
<p>Use the form below to contact us about your great ideas.</p>

app/views/home/index.html.erb
<h2>Latest Recipes</h2>
<p>There are <%= @number_of_recipes %> recipes total.</p>
=======
<%= render "/shared/search" %>
<h2>Latest Recipes</h2>
<p>There are <%= @number_of_recipes %> recipes total.</p>
<h3>Latest Recipe</h3>
<% if @latest_recipe %>
   <h4><%=@latest_recipe.title %></h4>
   <p><%=@latest_recipe.ingredients %></p>
   <p><%=@latest_recipe.instructions %></p>
<% else %>
   <p>There are no recipes to display</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
    <html lang="en-US">  
    <head>    
        <title><%= @title %></title>    
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>    
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>    
        <%= csrf_meta_tags %>  
    </head>  
    <body>    
        <div class="container">      
            <header>        
                <h1>Our Cookbook</h1>       
            </header>
            <nav>   
                <%=link_to_unless_current 'Home', root_url %>
                <%=link_to_unless_current 'Recipes', recipes_url %>
                <%=link_to_unless_current 'Categories', categories_url %>
                <%=link_to_unless_current 'About', about_url %>
                <%=link_to 'New recipe', new_recipe_path %>
            </nav>
            
            <% if notice %>
              <div id = "notice">
                <%= notice %>
              </div>
            <% end %>
            
            <section class="content">        
                <%= yield %>       
            </section>      
            <footer>        
                <h4>Copyright <%=Date.today.year %> OurCookbook</h4>      
            </footer>    
        </div>  
    </body> 
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>*<br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :ingredients %>*<br>
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :instructions %>*<br>
    <%= f.text_area :instructions %>
  </div>
  <div class="field">
    <%= f.label :calories %><br>
    <%= f.text_area :calories %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.select :category_id, @categories, :include_blank => true %>
  </div>
  <div><small>* - denotes required field.</small></div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<%= render "/shared/search" %>
<p id="notice"><%= notice %></p>

<h1>Listing Recipes</h1>
<% if logged_in? %>
You are logged in as <%= current_user.username %>
<% end %>

<table>

  <tr> 
    <th>Title</th>
    <th>Category</th>
    <th>Last Updated</th>
    <th colspan="2">&nbsp;</th>
  </tr>

  <% @recipes.each do |recipe| %>
    <tr>
      <td><%= link_to recipe.title, recipe %></td>
      <td><%= recipe.category.name rescue "No category" %></td>
      <td><%= time_ago_in_words(recipe.updated_at) %> ago</td>
      <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
      <td><%= button_to 'Destroy', recipe, confirm: 'Are you sure?', method: :delete %></td>     
    </tr>
  <% end %>
</table>

<% if logged_in? %>
  <%= link_to 'New recipe', new_recipe_path %>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<article>
  <header>
    <h2>
      <%= @recipe.title %>
      [ <%= link_to 'Edit', edit_recipe_path(@recipe) %> ]
    </h2>
  </header>
  
  <p>Category: <%= link_to @recipe.category.name, @recipe.category rescue 'No Category Found' %></p>
  
  
  <h3>Ingredients:</h3>
  <p><%= @recipe.ingredients %></p>
  
  <h3>Instructions</h3>
  <p><%= @recipe.instructions %></p>
  
  <h3>Calories</h3>
  <p><%= @recipe.calories %></p>
  
</article>

<p><%= link_to 'Back', recipes_path %></p>

app/views/shared/_search.html.erb
<%= form_tag recipes_url, method: :get do %>  
    <label for="query">Keywords: </label> 
    <input type="search" id="query" name="q" value="<%= params[:q] %>">
    <%= select("post", "name", Category.all.collect {|t| [ t.name ] }, {include_blank: 'None'})%>
    <input type="submit" value="Search"> 
<% end %> 